---
- hosts: # Nodo objetivo
  become: True
  vars_files: # Fichero de variables
  tasks:
    - name: Download One Agent from Dynatrace
      get_url:
        url: # dynatrace_url
        dest: # dynatrace_installer_path
        headers:
          Authorization: # "Api-Token dynatrace_token"

    - name: Download Certificate from Dynatrace
      get_url:
        url: # dynatrace_cert_url
        dest: "/tmp/dt-root.cert.pem"

    - name: Verify installer signature
      # shell: |
      #   ( echo 'Content-Type: multipart/signed; protocol="application/x-pkcs7-signature"; micalg="sha-256"; boundary="--SIGNED-INSTALLER"'; echo ; echo ; echo '----SIGNED-INSTALLER' ; cat dynatrace_installer_path ) | openssl cms -verify -CAfile /tmp/dt-root.cert.pem > /dev/null
      register: result
      ignore_errors: True

    - name: Install OneAgent
      # shell: "/bin/sh dynatrace_installer_path --set-monitoring-mode=fullstack --set-app-log-content-access=true"
      when: result.rc == 0
